title: Blend Vocal - Calgary Community Treble Choir
description: A welcoming treble choir in Calgary
url: https://blendvocal.ca
locale: en
theme: null
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache   # supported by GitHub Pages
  - jekyll-seo-tag
  - jekyll-sitemap
minimal_mistakes_skin: default
logo: /assets/img/favicon.svg
permalink: /:path/
collections: []
include:
  - _pages
  - robots.txt
author:
  name: "Blend Vocal Association of Calgary"
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/blendvocal/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/BlendVocalAssociation"  

footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/blendvocal/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/BlendVocalAssociation"  
